sudo: false
language: c
addons:
  apt:
    packages:
      - python-nose
env:
 - REPO=epics-base BRANCH=3.14
 - REPO=epics-base BRANCH=3.15
 - REPO=epics-base BRANCH=3.16
 - REPO=epics-base BRANCH=7.0
 - REPO=mdavidsaver BRANCH=integration
cache:
  directories:
   - $HOME/.cache
install: ./build-deps.sh
script:
 - . ./env; SOFTIOC=$EPICS_BASE/bin/linux-x86_64/softIoc DUT=$PWD/wrapioc.sh nosetests catvs.server
 - make -C pcastest
 - EPICS_CAS_INTF_ADDR_LIST=localhost DUT=$PWD/pcastest/bin/linux-x86_64/pcas nosetests catvs.server
